/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobaaccess;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FormKategori extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelKategori = new DefaultTableModel();

    /**
     * Creates new form FormKategori
     */
    public FormKategori() {
        initComponents();
        tblKategori.setModel(modelKategori);
        modelKategori.addColumn("Id_Kategori");
        modelKategori.addColumn("Nama_Kategori");

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://E:\\Semester 6\\Pembrograman Basis Data (Kojul)\\Penjualan.accdb");

            pst = conn.prepareStatement("select * from kategori ");
            rs = pst.executeQuery();
            modelKategori.setRowCount(0);
            while (rs.next()) {
                Object[] data = new Object[2];
                data[0] = rs.getString("Id_Kategori");
                data[1] = rs.getString("Nama_Kategori");
                modelKategori.addRow(data);
            }
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void reset() {
        tfId_Kategori.setText("");
        tfNama_Kategori.setText("");
        tfId_Kategori.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfId_Kategori = new javax.swing.JTextField();
        tfNama_Kategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Form Kategori");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Id_Kategori");

        jLabel3.setText("Nama_Kategori");

        tfId_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfId_KategoriActionPerformed(evt);
            }
        });

        tfNama_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNama_KategoriActionPerformed(evt);
            }
        });

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKategori);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfId_Kategori, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(tfNama_Kategori))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(btnUbah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNama_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfId_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfId_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfId_KategoriActionPerformed

    private void tfNama_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNama_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNama_KategoriActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String namaKategori = tfNama_Kategori.getText();
        char[] arrHuruf = namaKategori.toCharArray();
        int panjangKalimat = arrHuruf.length;
        if (panjangKalimat >= 3) {
            try {
                pst = conn.prepareStatement("insert into kategori(Id_Kategori,Nama_Kategori) values (?,?)");
                pst.setString(1, tfId_Kategori.getText());
                pst.setString(2, tfNama_Kategori.getText());

                int jum = pst.executeUpdate();
                if (jum > 0) {
                    JOptionPane.showMessageDialog(null, "Tersimpan");
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal");
                }
                pst.close();

                reset();
                pst = conn.prepareStatement("select * from kategori");
                rs = pst.executeQuery();
                modelKategori.setRowCount(0);
                while (rs.next()) {
                    Object[] data = new Object[2];
                    data[0] = rs.getString("Id_Kategori");
                    data[1] = rs.getString("Nama_Kategori");
                    modelKategori.addRow(data);
                }
                pst.close();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nama Ketergoi harus minimal 3 karakter");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {

            pst = conn.prepareStatement("update kategori set Nama_Kategori=? where Id_Kategori=?");
            pst.setString(2, tfId_Kategori.getText());
            pst.setString(1, tfNama_Kategori.getText());

            int jum = pst.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Terubah");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            pst.close();

            reset();

            pst = conn.prepareStatement("select * from kategori");
            rs = pst.executeQuery();
            modelKategori.setRowCount(0);
            while (rs.next()) {
                Object[] data = new Object[2];
                data[0] = rs.getString("Id_Kategori");
                data[1] = rs.getString("Nama_Kategori");
                modelKategori.addRow(data);
            }
            pst.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
        // TODO add your handling code here:
        int baris = tblKategori.getSelectedRow();
        tfId_Kategori.setText(tblKategori.getModel().getValueAt(baris, 0).toString());
        tfNama_Kategori.setText(tblKategori.getModel().getValueAt(baris, 1).toString());
        tfId_Kategori.grabFocus();
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {

            pst = conn.prepareStatement("delete kategori where Id_Kategori=?");
            pst.setString(1, tfId_Kategori.getText());

            int jum = pst.executeUpdate();
            if (jum > 0) {
                JOptionPane.showMessageDialog(null, "Terhapus");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            pst.close();

            reset();

            pst = conn.prepareStatement("select * from kategori");
            rs = pst.executeQuery();
            modelKategori.setRowCount(0);
            while (rs.next()) {
                Object[] data = new Object[2];
                data[0] = rs.getString("Id_Kategori");
                data[1] = rs.getString("Nama_Kategori");
                modelKategori.addRow(data);
            }
            pst.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField tfId_Kategori;
    private javax.swing.JTextField tfNama_Kategori;
    // End of variables declaration//GEN-END:variables

}
