/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobaaccess;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julia
 */
public class FormPengguna extends javax.swing.JFrame {

    /**
     * Creates new form FormPengguna
     */
    Connection conn;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelPengguna = new DefaultTableModel();
    
    public FormPengguna() {
        initComponents();
        tblPengguna.setModel(modelPengguna);
        modelPengguna.addColumn("ID");
        modelPengguna.addColumn("Nama");
        modelPengguna.addColumn("Pass");
        modelPengguna.addColumn("Lahir");
        modelPengguna.addColumn("Agama");
        modelPengguna.addColumn("Kelamin");
        modelPengguna.addColumn("Gaji");
        modelPengguna.addColumn("Jabatan");
        modelPengguna.addColumn("Status");
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://E:\\Semester 6\\Pembrograman Basis Data (Kojul)\\Penjualan.accdb");
        
            pst = conn.prepareStatement("select * from pengguna");
            rs = pst.executeQuery();
            modelPengguna.setRowCount(0);
            while (rs.next()) {
                Object[] data=new Object[9];
                data[0]=rs.getString("id");
                data[1]=rs.getString("nama");
                data[2]=rs.getString("password");
                data[3]=rs.getDate("tgl_lahir");
                data[4]=rs.getString("agama");
                data[5]=rs.getString("kelamin");
                data[6]=rs.getInt("gaji");
                data[7]=rs.getString("jabatan");
                data[8]=rs.getString("status");
                modelPengguna.addRow(data);
            }
            pst.close();
        } catch (Exception ex) {
            //System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        cbJabatan = new javax.swing.JComboBox<>();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        txtGaji = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengguna = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA");

        jLabel3.setText("PASSWORD");

        jLabel4.setText("TGL LAHIR");

        jLabel5.setText("AGAMA");

        jLabel6.setText("KELAMIN");

        jLabel7.setText("GAJI");

        jLabel8.setText("JABATAN");

        cbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemilik", "Kasir", "Gudang" }));
        cbJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJabatanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbLaki);
        rbLaki.setSelected(true);
        rbLaki.setText("Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setToolTipText("");
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Buddha", "Konghucu" }));

        tblPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPengguna);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel9.setText("Status");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Pasif" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(77, 77, 77)
                        .addComponent(cbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(44, 44, 44)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGaji)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbPerempuan))
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtID)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(cbAgama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbLaki)
                            .addComponent(rbPerempuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void reset() {
        txtID.setText("");
        txtNama.setText("");
        txtPass.setText("");
        txtTgl.setText("");
        cbAgama.setSelectedIndex(0);
        rbLaki.setSelected(true);
        txtGaji.setText("");
        cbJabatan.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        txtID.grabFocus();
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            String jkel;
            if (rbLaki.isSelected()) {
                jkel="Laki";
            } else {
                jkel="Perempuan";
            }
            
            pst= conn.prepareStatement("insert into pengguna(id,nama,password,tgl_lahir,agama,kelamin,gaji,jabatan,status) values (?,?,?,?,?,?,?,?,?)");
            pst.setString(1, txtID.getText());
            pst.setString(2, txtNama.getText());
            pst.setString(3, txtPass.getText());
            pst.setDate(4, java.sql.Date.valueOf(txtTgl.getText().replace("/", "-")));
            pst.setString(5, cbAgama.getSelectedItem().toString());
            pst.setString(6, jkel);
            pst.setInt(7, Integer.parseInt(txtGaji.getText()));
            pst.setString(8, cbJabatan.getSelectedItem().toString()); 
            pst.setString(9, cbStatus.getSelectedItem().toString()); 
            
            int jum = pst.executeUpdate();
            if (jum>0) {
                JOptionPane.showMessageDialog(null, "Tersimpan");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            pst.close();
            
            reset();
            
            pst = conn.prepareStatement("select * from pengguna");
            rs = pst.executeQuery();
            modelPengguna.setRowCount(0);
            while (rs.next()) {
                Object[] data=new Object[9];
                data[0]=rs.getString("id");
                data[1]=rs.getString("nama");
                data[2]=rs.getString("password");
                data[3]=rs.getDate("tgl_lahir");
                data[4]=rs.getString("agama");
                data[5]=rs.getString("kelamin");
                data[6]=rs.getInt("gaji");
                data[7]=rs.getString("jabatan");
                data[8]=rs.getString("status");
                modelPengguna.addRow(data);
            }
            pst.close();
            /*
            st=conn.createStatement();
            int jum = st.executeUpdate("insert into pengguna"
                    + "(id,nama,password,tgl_lahir,agama,kelamin,gaji,jabatan) values "
                    + "('" + txtID.getText() + "','" + txtNama.getText() + "','" + 
                    txtPass.getText() + "',#" + txtTgl.getText() + "#,'" + 
                    cbAgama.getSelectedItem().toString() + "', '" + jkel + "', " + 
                    txtGaji.getText() + ",'" + cbJabatan.getSelectedItem().toString() + "')");
            
            if (jum>0) {
                JOptionPane.showMessageDialog(null, "Tersimpan");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            st.close(); */
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenggunaMouseClicked
        // TODO add your handling code here:
        int baris = tblPengguna.getSelectedRow();
        txtID.setText(tblPengguna.getModel().getValueAt(baris, 0).toString());
        txtNama.setText(tblPengguna.getModel().getValueAt(baris, 1).toString());
        txtPass.setText(tblPengguna.getModel().getValueAt(baris, 2).toString());
        txtTgl.setText(tblPengguna.getModel().getValueAt(baris, 3).toString());
        cbAgama.setSelectedItem(tblPengguna.getModel().getValueAt(baris, 4).toString());
        if (tblPengguna.getModel().getValueAt(baris, 5).toString().equals("Laki")) {
            rbLaki.setSelected(true);
        } else {
            rbPerempuan.setSelected(true);
        }
        txtGaji.setText(tblPengguna.getModel().getValueAt(baris, 6).toString());
        cbJabatan.setSelectedItem(tblPengguna.getModel().getValueAt(baris, 7).toString());
        cbStatus.setSelectedItem(tblPengguna.getModel().getValueAt(baris, 8).toString());
        txtID.grabFocus();
    }//GEN-LAST:event_tblPenggunaMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            String jkel;
            if (rbLaki.isSelected()) {
                jkel="Laki";
            } else {
                jkel="Perempuan";
            }
            
            pst= conn.prepareStatement("update pengguna set nama=?,password=?,tgl_lahir=?,agama=?,kelamin=?,gaji=?,jabatan=?,status=? where id=?");
            pst.setString(9, txtID.getText());
            pst.setString(1, txtNama.getText());
            pst.setString(2, txtPass.getText());
            pst.setDate(3, java.sql.Date.valueOf(txtTgl.getText().replace("/", "-")));
            pst.setString(4, cbAgama.getSelectedItem().toString());
            pst.setString(5, jkel);
            pst.setInt(6, Integer.parseInt(txtGaji.getText()));
            pst.setString(7, cbJabatan.getSelectedItem().toString());
            pst.setString(8, cbStatus.getSelectedItem().toString());
            
            int jum = pst.executeUpdate();
            if (jum>0) {
                JOptionPane.showMessageDialog(null, "Terubah");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            pst.close();
            
            reset();
            
            pst = conn.prepareStatement("select * from pengguna");
            rs = pst.executeQuery();
            modelPengguna.setRowCount(0);
            while (rs.next()) {
                Object[] data=new Object[9];
                data[0]=rs.getString("id");
                data[1]=rs.getString("nama");
                data[2]=rs.getString("password");
                data[3]=rs.getDate("tgl_lahir");
                data[4]=rs.getString("agama");
                data[5]=rs.getString("kelamin");
                data[6]=rs.getInt("gaji");
                data[7]=rs.getString("jabatan");
                data[8]=rs.getString("status");
                modelPengguna.addRow(data);
            }
            pst.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
           
            pst= conn.prepareStatement("delete pengguna where id=?");
            pst.setString(1, txtID.getText());
           
            int jum = pst.executeUpdate();
            if (jum>0) {
                JOptionPane.showMessageDialog(null, "Terhapus");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
            pst.close();
            
            reset();
            
            pst = conn.prepareStatement("select * from pengguna");
            rs = pst.executeQuery();
            modelPengguna.setRowCount(0);
            while (rs.next()) {
                Object[] data=new Object[9];
                data[0]=rs.getString("id");
                data[1]=rs.getString("nama");
                data[2]=rs.getString("password");
                data[3]=rs.getDate("tgl_lahir");
                data[4]=rs.getString("agama");
                data[5]=rs.getString("kelamin");
                data[6]=rs.getInt("gaji");
                data[7]=rs.getString("jabatan");
                data[8]=rs.getString("status");
                modelPengguna.addRow(data);
            }
            pst.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tblPengguna;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
